### ISSUE TITLE
No moduled 'termcolor' 

### ISSUE THREAD

**Issue by SantriInsyaf** [galehrizky/wp-brute-xmlrpc#3]
I have install termcolor with command pip install termcolor but the answer when i run this tools => no moduled 'termcolor'
I have check and the termcolor have install in python2 how to fix it slur?

**Comment by apaajalahx** [comment]
Has it been installed successfully? or do you use python3?
if you use python3 try install 'termcolor' again with command
```
python3 -m pip install termcolor
```

**Comment by SantriInsyaf** [comment]
Ga bisa slur, pake termux ini. Pas install python3, masuknya ke python. Nah pas install modulenya malah masuk python2. Pusing dah :(
